// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM1ACsXdFRR5KtumXdsP3h4Kk8XDe1nHI',
    appId: '1:60183775527:web:09a3e485884b081c674102',
    messagingSenderId: '60183775527',
    projectId: 'prototype-29c26',
    authDomain: 'prototype-29c26.firebaseapp.com',
    databaseURL: 'https://prototype-29c26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prototype-29c26.firebasestorage.app',
    measurementId: 'G-NH61R1GQZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnTEc3b6qOfjFUPuXK4RMf8O8dDNBjz1s',
    appId: '1:60183775527:android:efd28f0a996a0085674102',
    messagingSenderId: '60183775527',
    projectId: 'prototype-29c26',
    databaseURL: 'https://prototype-29c26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prototype-29c26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvV6s1VmRpvH8uI9UZAfZzTLk9pbINXiQ',
    appId: '1:60183775527:ios:e4cd05cc89685cca674102',
    messagingSenderId: '60183775527',
    projectId: 'prototype-29c26',
    databaseURL: 'https://prototype-29c26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prototype-29c26.firebasestorage.app',
    androidClientId: '60183775527-4o1f51fkpqsk4jfu8ij9h9rleuk8qp74.apps.googleusercontent.com',
    iosClientId: '60183775527-qdd6vg300iucjum8b2ulfr9jjucvpcfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.freegramFreshStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvV6s1VmRpvH8uI9UZAfZzTLk9pbINXiQ',
    appId: '1:60183775527:ios:e4cd05cc89685cca674102',
    messagingSenderId: '60183775527',
    projectId: 'prototype-29c26',
    databaseURL: 'https://prototype-29c26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prototype-29c26.firebasestorage.app',
    androidClientId: '60183775527-4o1f51fkpqsk4jfu8ij9h9rleuk8qp74.apps.googleusercontent.com',
    iosClientId: '60183775527-qdd6vg300iucjum8b2ulfr9jjucvpcfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.freegramFreshStart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM1ACsXdFRR5KtumXdsP3h4Kk8XDe1nHI',
    appId: '1:60183775527:web:2050b80db184fc5a674102',
    messagingSenderId: '60183775527',
    projectId: 'prototype-29c26',
    authDomain: 'prototype-29c26.firebaseapp.com',
    databaseURL: 'https://prototype-29c26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'prototype-29c26.firebasestorage.app',
    measurementId: 'G-WWYK9SJX3X',
  );

}