// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ??
            'AIzaSyDM1ACsXdFRR5KtumXdsP3h4Kk8XDe1nHI',
        appId: dotenv.env['FIREBASE_WEB_APP_ID'] ??
            '1:60183775527:web:c69ff7a2c243fe95674102',
        messagingSenderId:
            dotenv.env['FIREBASE_WEB_MESSAGING_SENDER_ID'] ?? '60183775527',
        projectId: dotenv.env['FIREBASE_WEB_PROJECT_ID'] ?? 'prototype-29c26',
        authDomain: dotenv.env['FIREBASE_WEB_AUTH_DOMAIN'] ??
            'prototype-29c26.firebaseapp.com',
        databaseURL: dotenv.env['FIREBASE_WEB_DATABASE_URL'] ??
            'https://prototype-29c26-default-rtdb.europe-west1.firebasedatabase.app',
        storageBucket: dotenv.env['FIREBASE_WEB_STORAGE_BUCKET'] ??
            'prototype-29c26.firebasestorage.app',
        measurementId:
            dotenv.env['FIREBASE_WEB_MEASUREMENT_ID'] ?? 'G-EBLPZVBM3Y',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ??
            'AIzaSyDnTEc3b6qOfjFUPuXK4RMf8O8dDNBjz1s',
        appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ??
            '1:60183775527:android:ee81b78fe213d33b674102',
        messagingSenderId:
            dotenv.env['FIREBASE_ANDROID_MESSAGING_SENDER_ID'] ?? '60183775527',
        projectId:
            dotenv.env['FIREBASE_ANDROID_PROJECT_ID'] ?? 'prototype-29c26',
        databaseURL: dotenv.env['FIREBASE_ANDROID_DATABASE_URL'] ??
            'https://prototype-29c26-default-rtdb.europe-west1.firebasedatabase.app',
        storageBucket: dotenv.env['FIREBASE_ANDROID_STORAGE_BUCKET'] ??
            'prototype-29c26.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ??
            'AIzaSyAvV6s1VmRpvH8uI9UZAfZzTLk9pbINXiQ',
        appId: dotenv.env['FIREBASE_IOS_APP_ID'] ??
            '1:60183775527:ios:df7206a6a5f5278c674102',
        messagingSenderId:
            dotenv.env['FIREBASE_IOS_MESSAGING_SENDER_ID'] ?? '60183775527',
        projectId: dotenv.env['FIREBASE_IOS_PROJECT_ID'] ?? 'prototype-29c26',
        databaseURL: dotenv.env['FIREBASE_IOS_DATABASE_URL'] ??
            'https://prototype-29c26-default-rtdb.europe-west1.firebasedatabase.app',
        storageBucket: dotenv.env['FIREBASE_IOS_STORAGE_BUCKET'] ??
            'prototype-29c26.firebasestorage.app',
        androidClientId: dotenv.env['FIREBASE_IOS_ANDROID_CLIENT_ID'] ??
            '60183775527-2t0jjrovodmnurvlj7g3afdkhiuf0921.apps.googleusercontent.com',
        iosClientId: dotenv.env['FIREBASE_IOS_IOS_CLIENT_ID'] ??
            '60183775527-t9uis8e2t1011048nnrsnl02emula68s.apps.googleusercontent.com',
        iosBundleId: 'com.freegram.app',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_MACOS_API_KEY'] ??
            'AIzaSyAvV6s1VmRpvH8uI9UZAfZzTLk9pbINXiQ',
        appId: dotenv.env['FIREBASE_MACOS_APP_ID'] ??
            '1:60183775527:ios:df7206a6a5f5278c674102',
        messagingSenderId:
            dotenv.env['FIREBASE_MACOS_MESSAGING_SENDER_ID'] ?? '60183775527',
        projectId: dotenv.env['FIREBASE_MACOS_PROJECT_ID'] ?? 'prototype-29c26',
        databaseURL: dotenv.env['FIREBASE_MACOS_DATABASE_URL'] ??
            'https://prototype-29c26-default-rtdb.europe-west1.firebasedatabase.app',
        storageBucket: dotenv.env['FIREBASE_MACOS_STORAGE_BUCKET'] ??
            'prototype-29c26.firebasestorage.app',
        androidClientId: dotenv.env['FIREBASE_MACOS_ANDROID_CLIENT_ID'] ??
            '60183775527-2t0jjrovodmnurvlj7g3afdkhiuf0921.apps.googleusercontent.com',
        iosClientId: dotenv.env['FIREBASE_MACOS_IOS_CLIENT_ID'] ??
            '60183775527-t9uis8e2t1011048nnrsnl02emula68s.apps.googleusercontent.com',
        iosBundleId: 'com.freegram.app',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ??
            'AIzaSyDM1ACsXdFRR5KtumXdsP3h4Kk8XDe1nHI',
        appId: dotenv.env['FIREBASE_WINDOWS_APP_ID'] ??
            '1:60183775527:web:2050b80db184fc5a674102',
        messagingSenderId:
            dotenv.env['FIREBASE_WINDOWS_MESSAGING_SENDER_ID'] ?? '60183775527',
        projectId:
            dotenv.env['FIREBASE_WINDOWS_PROJECT_ID'] ?? 'prototype-29c26',
        authDomain: dotenv.env['FIREBASE_WINDOWS_AUTH_DOMAIN'] ??
            'prototype-29c26.firebaseapp.com',
        databaseURL: dotenv.env['FIREBASE_WINDOWS_DATABASE_URL'] ??
            'https://prototype-29c26-default-rtdb.europe-west1.firebasedatabase.app',
        storageBucket: dotenv.env['FIREBASE_WINDOWS_STORAGE_BUCKET'] ??
            'prototype-29c26.firebasestorage.app',
        measurementId:
            dotenv.env['FIREBASE_WINDOWS_MEASUREMENT_ID'] ?? 'G-WWYK9SJX3X',
      );
}
